#!/bin/sh

apt install golang-1.18-go

version="$(/opt/gitlab/embedded/bin/gitlab-workhorse -version | grep -Eo 'v[^)]+')"
git clone --depth=1 --branch="$version" https://gitlab.com/gitlab-org/gitlab
cd gitlab/workhorse

file="internal/upload/destination/objectstore/s3_object.go"; \
script='s/s3manager\.NewUploader\(sess\)/s3manager.NewUploader(sess, func(u *s3manager.Uploader) { u.PartSize = 64 * 1024 * 1024 })/'; \
sed -E -i.orig -- "$script" "$file" && ! diff -u -- "$file.orig" "$file"

/usr/lib/go-1.18/bin/go build
mv workhorse /opt/gitlab/embedded/bin/gitlab-workhorse

file="/opt/gitlab/embedded/service/gitlab-rails/config/initializers/carrierwave_patch.rb"; \
script='s/file\.multipart_chunk_size = 10485760/file.multipart_chunk_size = 10485760 / 10 * 1024/'; \
sed -E -i.orig -- "$script" "$file" && ! diff -u -- "$file.orig" "$file"
