#!/bin/sh -eu

: "${DOMAIN_SUFFIX=fr.bw-cloud-instance.org}"

: "${AWS_ENDPOINT_URL=https://s3.bwsfs.uni-freiburg.de/}"
: "$AWS_ACCESS_KEY_ID"
: "$AWS_SECRET_ACCESS_KEY"
: "${AWS_REGION=fr-repl}"

: "$BUCKET"

domain="$(cat /var/lib/cloud/data/instance-id).$DOMAIN_SUFFIX"

case "$0" in /var/lib/cloud/instance/scripts/*)
   # if grep -q /usr/bin/cloud-init "/proc/$SYSTEMD_EXEC_PID/cmdline"; then
   # case "$(realpath -- "/proc/$SYSTEMD_EXEC_PID/fd/3")" in /var/log/cloud-init.log)
   curl -fL https://github.com/emulation-as-a-service/cloud-init-update/raw/main/user-data | sh

   hostnamectl hostname -- "${domain%%-*}"
   hostnamectl hostname --pretty -- "GitLab: https://$domain $(hostnamectl hostname --pretty)"

   apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git git-lfs
   ;;
esac

: <<"EOF"
# Alternative using docker-compose:
# https://docs.gitlab.com/ee/install/docker.html#install-gitlab-using-docker-compose

sudo apt-get install -y docker-compose

sed -i 's/\$GITLAB_HOME/./' docker-compose.yaml
sed -i "s/gitlab.example.com/$(cat /var/lib/cloud/data/instance-id).$DOMAIN_SUFFIX/" docker-compose.yaml 

sudo compose exec . web cat /etc/gitlab/initial_root_password
EOF

# https://about.gitlab.com/install/#ubuntu
curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | sudo bash

sudo EXTERNAL_URL="https://$domain" apt-get install gitlab-ee

sudo tee -a /etc/gitlab/gitlab.rb <<EOF

# https://docs.gitlab.com/ee/administration/operations/puma.html#change-the-worker-timeout
# https://www.rubydoc.info/gems/puma/Puma%2FDSL:worker_timeout
# https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/6337
# puma['worker_timeout'] = 600

gitlab_rails['env'] = {
   'GITLAB_RAILS_RACK_TIMEOUT' => 600
}

# https://gitlab.com/gitlab-org/gitlab/-/issues/373743
postgresql['idle_in_transaction_session_timeout'] = "360000"

# https://docs.gitlab.com/ee/administration/object_storage.html
gitlab_rails['object_store']['enabled'] = true
gitlab_rails['object_store']['connection'] = {
   'provider' => 'AWS',
   'endpoint' => '$AWS_ENDPOINT_URL',
   'region' => '$AWS_REGION',
   'aws_access_key_id' => '$AWS_ACCESS_KEY_ID',
   'aws_secret_access_key' => '$AWS_SECRET_ACCESS_KEY',
   'bucket' => '$BUCKET',
}
gitlab_rails['object_store']['objects']['artifacts']['bucket'] =
gitlab_rails['object_store']['objects']['external_diffs']['bucket'] =
gitlab_rails['object_store']['objects']['lfs']['bucket'] =
gitlab_rails['object_store']['objects']['uploads']['bucket'] =
gitlab_rails['object_store']['objects']['packages']['bucket'] =
gitlab_rails['object_store']['objects']['dependency_proxy']['bucket'] =
gitlab_rails['object_store']['objects']['terraform_state']['bucket'] =
gitlab_rails['object_store']['objects']['ci_secure_files']['bucket'] =
gitlab_rails['object_store']['objects']['pages']['bucket'] =
gitlab_rails['object_store']['connection']['bucket']
EOF

sudo gitlab-ctl reconfigure
